workflows:
  sample-workflow:
    environment:
      flutter: stable
    scripts:
      - name: Set iOS deployment target to 13.0
        script: |
          if [ -f ios/Podfile ]; then
            sed -i '' 's/platform :ios, '9.0'/platform :ios, '13.0'/' ios/Podfile
          else
            echo "platform :ios, '13.0'" > ios/Podfile
          fi
          echo "Updated Podfile to iOS 13.0"

      - name: Ensure iOS workspace is properly generated
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          flutter clean
          flutter pub get
          flutter build ios --no-codesign
          pod install --verbose
          cd ..


      - name: Install Android dependencies
        script: |
          flutter pub get

      - name: Build Android
        script: |
          flutter build apk

      - name: Build iOS
        script: |
          flutter build ios --no-codesign

      - name: Publish Artifacts (Optional)
        script: |
          mkdir -p build_outputs
          mv build/app/outputs/flutter-apk/app-release.apk build_outputs/
          echo "Artifacts moved for publishing"
