workflows:
  sample-workflow:
    environment:
      flutter: stable

    scripts:
      - name: Set iOS deployment target to 13.0
        script: |
          if [ -f ios/Podfile ]; then
            sed -i '' 's/platform :ios, '9.0'/platform :ios, '13.0'/' ios/Podfile
          else
            echo "platform :ios, '13.0'" > ios/Podfile
          fi
          echo "Updated Podfile to iOS 13.0"

      - name: Ensure iOS workspace is properly generated
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          flutter clean
          flutter pub get
          pod deintegrate
          pod setup
          flutter build ios --no-codesign
          pod install --verbose
          cd ..

      - name: Install Android dependencies
        script: |
          flutter pub get

      - name: Build iOS (IPA)
        script: |
          cd ios
          xcodebuild -scheme Runner -sdk iphoneos -configuration Release archive -archivePath build/Runner.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath build/ios/ipa
          cd ..
          echo "iOS IPA build completed"

      - name: Build Android (APK)
        script: |
          flutter build apk
          echo "Android APK build completed"

      - name: Publish Artifacts
        script: |
          mkdir -p build_outputs
          cp build/app/outputs/flutter-apk/app-release.apk build_outputs/
          cp -r build/ios/ipa/*.ipa build_outputs/
          echo "Artifacts copied for publishing"

    artifacts:
      - build_outputs/app-release.apk
      - build_outputs/*.ipas
