workflows:
  ios-ipa:
    name: iOS IPA Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - signing_credentials
      ios_signing:
        distribution_type: ad_hoc  # Change to development if testing locally
        bundle_identifier: "com.yourcompany.yourapp"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Flutter build
        script: |
          flutter build ios --release --no-codesign
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.yourcompany.yourapp" --type IOS_APP_ADHOC
      - name: Build iOS IPA
        script: |
          xcode-project use-profiles
          xcode-project build-ipa --workspace="ios/Runner.xcworkspace" --scheme="Runner"
    artifacts:
      - build/ios/ipa/*.ipa
