workflows:
  sample-workflow:
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.16.2

    scripts:
      # Use system Ruby (avoid installing manually)
      - name: Use System Ruby
        script: |
          ruby -v  # ✅ Check system Ruby version

      # Ensure iOS dependencies are generated before running CocoaPods
      - name: Ensure Flutter generates iOS dependencies
        script: |
          flutter pub get
          flutter pub run flutter_plugin_tools podspecs
          cd ios
          flutter build ios --no-codesign  # ✅ This regenerates the Podfile correctly
          cd ..
          echo "Flutter iOS dependencies generated"

      # Install CocoaPods
      - name: Install CocoaPods
        script: |
          gem install cocoapods -v 1.16.2
          pod repo update

      # Clean and Reinstall CocoaPods
      - name: Prepare iOS environment
        script: |
          cd ios
          rm -rf Pods Podfile.lock Runner.xcworkspace
          pod deintegrate
          pod install --repo-update
          cd ..
          echo "iOS environment prepared"

      # Ensure iOS Workspace is Generated
      - name: Ensure iOS workspace is created
        script: |
          cd ios
          pod install --repo-update
          if [ ! -f "Runner.xcworkspace" ]; then
            echo "❌ Missing xcworkspace! Pod installation failed."
            exit 1
          fi
          cd ..
          echo "iOS workspace setup completed"

      # Build iOS IPA
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Automatic \
            archive -archivePath $CM_BUILD_DIR/build/Runner.xcarchive | xcpretty
          if [ ! -d "$CM_BUILD_DIR/build/Runner.xcarchive" ]; then
            echo "❌ Xcode archive failed: Archive not found!"
            exit 1
          fi
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/Runner.xcarchive \
            -exportOptionsPlist ./exportOptions.plist -exportPath $CM_BUILD_DIR/build/ios/ipa | xcpretty
          cd ..
          echo "✅ iOS IPA build completed"

      # Build Android APK
      - name: Build Android (APK)
        script: |
          flutter build apk
          echo "✅ Android APK build completed"

      # Publish Artifacts
      - name: Publish Artifacts
        script: |
          mkdir -p build_outputs
          cp build/app/outputs/flutter-apk/app-release.apk build_outputs/
          [ -d build/ios/ipa ] && cp -r build/ios/ipa/*.ipa build_outputs/
          echo "✅ Artifacts copied for publishing"

    artifacts:
      - build_outputs/app-release.apk
      - build_outputs/*.ipa
