workflows:
  sample-workflow:
    environment:
      flutter: stable
    scripts:
      - name: Set iOS deployment target to 13.0
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 9.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/' ios/Runner.xcodeproj/project.pbxproj
          echo "Updated iOS deployment target to 13.0"

      - name: Ensure Podfile exists
        script: |
          if [ ! -f ios/Podfile ]; then
            cd ios
            flutter clean
            flutter pub get
            flutter build ios --no-codesign
            pod init
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Install Android dependencies
        script: |
          flutter pub get

      - name: Build Android
        script: |
          flutter build apk

      - name: Build iOS
        script: |
          flutter build ios --no-codesign

      - name: Publish Artifacts (Optional)
        script: |
          mkdir -p build_outputs
          mv build/app/outputs/flutter-apk/app-release.apk build_outputs/
          echo "Artifacts moved for publishing"
