workflows:
  sample-workflow:
    scripts:
      - name: Set iOS deployment target to 13.0
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 9.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/' ios/Runner.xcodeproj/project.pbxproj
          echo "Updated iOS deployment target to 13.0"

      - name: Ensure Podfile exists
        script: |
          if [ ! -f ios/Podfile ]; then
            cd ios
            flutter clean
            flutter pub get
            flutter build ios --no-codesign
            pod init
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
    
