// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFUpWO1lfI0oSyIqGeX1qMirMrQzIxUl4',
    appId: '1:1051126909814:web:a7533e7147b1527a03c857',
    messagingSenderId: '1051126909814',
    projectId: 'fmradio-4bfc5',
    authDomain: 'fmradio-4bfc5.firebaseapp.com',
    storageBucket: 'fmradio-4bfc5.firebasestorage.app',
    measurementId: 'G-3SG4SKRZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeJYJUtHFO117BAKxGb3YLUmUzUZljl44',
    appId: '1:1051126909814:android:2f73c37386d8c56a03c857',
    messagingSenderId: '1051126909814',
    projectId: 'fmradio-4bfc5',
    storageBucket: 'fmradio-4bfc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWpo7LUKPZhFF86n7Ki2lpTtEUI15VNo',
    appId: '1:1051126909814:ios:c7ec124e6cdf982e03c857',
    messagingSenderId: '1051126909814',
    projectId: 'fmradio-4bfc5',
    storageBucket: 'fmradio-4bfc5.firebasestorage.app',
    iosBundleId: 'com.example.fmRadio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIWpo7LUKPZhFF86n7Ki2lpTtEUI15VNo',
    appId: '1:1051126909814:ios:c7ec124e6cdf982e03c857',
    messagingSenderId: '1051126909814',
    projectId: 'fmradio-4bfc5',
    storageBucket: 'fmradio-4bfc5.firebasestorage.app',
    iosBundleId: 'com.example.fmRadio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFUpWO1lfI0oSyIqGeX1qMirMrQzIxUl4',
    appId: '1:1051126909814:web:a301bf99432d0a0d03c857',
    messagingSenderId: '1051126909814',
    projectId: 'fmradio-4bfc5',
    authDomain: 'fmradio-4bfc5.firebaseapp.com',
    storageBucket: 'fmradio-4bfc5.firebasestorage.app',
    measurementId: 'G-NT68BD2LS4',
  );
}
